### ISSUE TITLE
Can't read or write tiff format?

### ISSUE THREAD

**Issue by namejm** [afriess/dexif#3]
I convert \samples\pictures\pexels-photo-355241max.jpeg to pexels-photo-355241max.tif, then add the extendname .jpeg, so the name of the tif format file is **pexels-photo-355241max.tif.jpeg**, when I run ReadWriteTest.exe and click Test1 buttom, the issues occur, is dExif can't read or write tiff format?

![failedtoreadwritetiff](https://user-images.githubusercontent.com/31474998/30908689-f4a8c83e-a3b0-11e7-968a-1d2f620a9ef0.jpg)

**Comment by afriess** [comment]
If you change the extension of the file, you say the tif should read as a jpeg - and this cannot work. Look in dEXIF.pas around line 4230. So the message defective JPEG structure is correct.

Andreas
